### ISSUE TITLE
killproc is called without delay

### ISSUE THREAD

**Issue by giena** [id/kafka-rpm#12]
Hi!
I read your kafka init file and it calls killproc without delay to stop kafka.
killproc has a timeout of 3 seconds (on CentOS 7). After killproc kills (-9) the process.
If kafka does not terminate his flushes before the timeout, indexes won't be flushed and you will have some trouble during the next start.
I think it could be better if you pass a delay to killproc (option -d):
killproc -p $PIDFILE -d 60 $PROG

Bye.

**Comment by id** [comment]
Resolved in #13
